### ISSUE TITLE
Eighteen varieties form Word Plants with  parent id invalid 

### ISSUE THREAD

**Issue by DianRHR** [CatalogueOfLife/data#673] opened 2024-06-11 03:34 UTC
**Describe the problem**:
In the last xrelease I found 18 names of varieties placed under Unranked/ incertae sedis, but any of them comes from the merged sectors. 
Analysing all of the , I verified that they come from World Plants, and all of them have an error in the parentID 

**Link to effected CoL webpages**:
the names can be easily seen in https://www.checklistbank.org/dataset/298210/classification 
 but, they are not  visible in https://www.catalogueoflife.org/?taxonKey=4DYV
However, this example https://www.catalogueoflife.org/data/taxon/BP9WZ  shows that as an accepted name present in the COL but without higher classification. All the 18 varieties have the same problem.

**Comment by aoern** [comment] 2024-06-11 09:31
This issue seems to be a duplicate of issue #656.

**Comment by mdoering** [comment] 2024-06-11 10:08
@DianRHR The XReleases are not being shown on catalogueoflife.org yet, just in CLB

**Comment by mdoering** [comment] 2024-06-11 10:13
seems related to #656, but world plants now does not have any parentID issue any longer.
It is only the XCOL that it is being flagged for yet unknown reasons:

https://www.checklistbank.org/dataset/1141/taxon/Asterales-Asteraceae-Asteroideae-Ericameria-nauseosa-variety-salicifolia-(Rydb.)%20G.%20L.%20Nesom%20&%20G.%20I.%20Baird

**Comment by mdoering** [comment] 2024-06-11 10:15
@DianRHR please do not assign issues about the xcol to @yroskov and label all issues with [xcol](https://github.com/CatalogueOfLife/data/labels/xcol) and put them into the XCOL project under todo so we can organise them better.

**Closed** 2024-06-11 14:21 UTC
Labels: feedback, xcol
