### ISSUE TITLE
Begoniaceae family is missing on the last COL Release

### ISSUE THREAD

**Issue by camiplata** [CatalogueOfLife/data#683] opened 2024-07-08 16:24 UTC
**Describe the problem**:

Begoniaceae family  is missing from [COL24](https://www.checklistbank.org/dataset/299029/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nomCode&facet=nameType&facet=field&facet=authorship&facet=authorshipYear&facet=extinct&facet=environment&facet=origin&facet=sectorMode&facet=secondarySourceGroup&facet=sectorDatasetKey&facet=group&limit=50&offset=0&q=Begoniaceae&sortBy=taxonomic), it was present on [COL24.5](https://www.checklistbank.org/dataset/296511/taxon/75F)

<img width="576" alt="Captura de pantalla 2024-07-08 a la(s) 11 22 48 a m" src="https://github.com/CatalogueOfLife/data/assets/5700527/f944c3ad-6e68-4558-a670-3a3e9a9dedba">

The family is present at the source GSD https://www.checklistbank.org/dataset/1141/taxon/Cucurbitales-Begoniaceae

**Link to effected CoL webpages**:
https://www.catalogueoflife.org/data/taxon/75F

**Comment by mdoering** [comment] 2024-07-08 17:47
duplicate of https://github.com/CatalogueOfLife/data/issues/681

**Comment by yroskov** [comment] 2024-07-08 19:53
Correct: the family is present again in the new version of World Plants which we synced in July edition.

FIXED

**Closed by yroskov** 2024-07-08 19:53 UTC
Labels: feedback
