### ISSUE TITLE
Diacritical flip-flop back again?

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#180] opened 2020-10-01 18:57 UTC
Spelling of author names and infraspecific names containing diacritical marks seems to change more or less randomly between successive DwC editions.
@gdower , this behavior looks pretty much the same that you found and fixed more than a year ago.
The problem seems to appear in many datasets. Let's take FLADA Ephemeroptera as an example:
The spelling of author name Navás between the Aug and the Sep edition has changed as follows:
Navas -> Navás  58 times (Ok)
Navás -> Navas    6 times (Bad)
Navas - Navas (unchanged)  40 times
Navás - Navás (unchanged) 4 times

**Comment by yroskov** [comment] 2020-10-01 19:01
@gdower

**Comment by mdoering** [comment] 2020-10-02 05:08
There have been only [2 imports of FADA](https://data.catalogue.life/dataset/1120/imports) recently, in December 2019 and July 2020. [FADA has been synced 6 times](http://api.catalogue.life/dataset/3/sector/sync?datasetKey=1120&limit=10
) so far, with the latest one being in July 18th.

**Comment by yroskov** [comment] 2020-10-02 12:53
FADA data are fixed, they have not been updated/changed since its first entry in CoL in 2010-2013.

Flip-flop of characters with diacritics, as Geoff found few years ago, is caused by a bug/incorrect settings in Ruud's converter (or MySQL database?). Geoff fixed it in the code. Perhaps, incorrect code version was used in the conversion.

**Comment by mdoering** [comment] 2020-10-02 13:23
@aoern do you have some example names? Indeed a search for [Navas](https://data.catalogue.life/dataset/1120/verbatim?q=Navas) does not yield anything even in the verbatim search.

Found in [GBIF](https://www.gbif.org/species/search?q=Navas&highertaxon_key=1225&qField=SCIENTIFIC):
 - Callibaetis stictogaster Navas, 1915
 - Callibaetis jaffueli Navas, 1918
 - Baetis neglectus Navas, 1913

... but they are all not from and in CoL

**Comment by mdoering** [comment] 2020-10-02 13:31
Wow, found the genus _Eatonica_ by Navás:
https://data.catalogue.life/dataset/1120/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=50&offset=0&q=Eatonica&sortBy=taxonomic

which has [Eatonica schoutedeni (Navás, 1911)](https://data.catalogue.life/dataset/1120/taxon/9047)

But you cannot find it in the search. Filed an [issue](https://github.com/CatalogueOfLife/backend/issues/864) for it.

**Comment by yroskov** [comment] 2020-10-02 13:33
I succeeded to find example names using old interface:

ac19 Afronurus aethereus (Navás, 1936)
col: Afronurus aethereus (Navas, 1936)

ac19 Americabaetis albinervis (Navás, 1923)
col: Americabaetis albinervis (Navas, 1923)

ac19 Americabaetis bridarollii (Navás, 1933)
col: Americabaetis bridarollii (Navas, 1933)

ac19 Americabaetis bruchi (Navas, 1926)
col: Americabaetis bruchi (Navas, 1926)

**Comment by mdoering** [comment] 2020-10-02 13:37
the old interface doesnt let you search on author names at all ...

**Comment by yroskov** [comment] 2020-10-02 13:40
In old interface I have got a full species list of Ephemeroptera (browse - classification, 500 names per page), and searched for Navas in Firefox

**Comment by mdoering** [comment] 2020-10-02 13:40
It seems the ASCII folding from Navás to Navas is a problem. If CoL consistently uses Navás you cannot find it, that woud explain it. You cannot find any of those names in GBIF and postgres either so I fear its a generic unicode problem, see #864

**Comment by mdoering** [comment] 2020-10-02 13:42
Looks like the page size selector in the UI isnt working.
You can list 1000 species when changing the limit parameter in the URL manually:
https://data.catalogue.life/dataset/1120/names?facet=rank&facet=issue&facet=status&facet=nomStatus&facet=nameType&facet=field&limit=1000&offset=0&rank=species&reverse=false&sortBy=taxonomic

**Comment by gdower** [comment] 2020-10-02 16:12
Good catch, @aoern! The schema that causes the diacritics bug is in a different repo from the ConversionTool and didn't get pulled by the provisioning script. Maybe I should move BaseSchema into the ConversionTool repo? I don't think it would be hard to do and I think it would make sense to include them in the same repo, although it's fixed now and somewhat doubtful that I will rebuild the conversion machines again.

**Comment by aoern** [comment] 2020-10-02 18:23
Good work, @gdower! Thanks.

**Closed** 2020-10-06 14:17 UTC
Labels: feedback
