### ISSUE TITLE
Maintaining metadata

### ISSUE THREAD

**Issue by gdower** [CatalogueOfLife/data#110] opened 2020-02-24 22:12 UTC
Often metadata is not well maintained by data providers and it takes a lot of time to continually correct the metadata. These manual changes to metadata in the Clearinghouse can be overwritten by the importer from GitHub repo metadata.yaml files, or the SourceDatabase table for ACEF submissions. Ideally, we probably should curate the metadata in the metadata.yaml files so that we have a versioned history and can restore the metadata, but we will not always have a repo (and metadata.yaml) for all data sources (e.g., proxy datasets). This makes managing the metadata complicated, because there's no single place to curate the metadata, and the manual metadata changes have often been overwritten.

I might be able to write an application that watches the metadata in the Clearinghouse for changes and takes backup snapshots of it so that we can compare, merge, and correct the metadata when it gets overwritten, and hopefully make curating the metadata less time consuming. It might need a decisions system that will automatically correct past issues, and flag new changes for needing editorial review.

One possible approach might be dumping the metadata from the API into metadata.yaml files in a GitHub repo where it could all be managed in a single location with revision tracking, and used to repopulate the metadata in the Clearinghouse before releasing monthly editions.

After writing this, I saw this [related thread on possibly just locking the metadata](https://github.com/Sp2000/colplus-backend/issues/553), but we probably need to be able selectively allow good metadata updates, flag unknown changes for review, and block known bad updates.

**Comment by mdoering** [comment] 2020-02-25 09:12
@gdower you can already lock metadata so it does not get overwritten by imports.
It only works on all fields though, but we could extend the idea to only partially lock fields. 

I don't think it is a good idea to create a lot of management tools and repos outside the Clearinghouse. We should rather adapt it to our needs.

The main problem I see with dataset metadata is that you might want the CoL source dataset metadata (as used in a release) to be slightly different from the full dataset that got imported, e.g. ITIS or IRMNG. 

I am also not convinced that it is a good idea to manually change whatever was given in a dataset. The publisher of the data should have full control and when we declares metadata it should be used. 

Both these arguments point to me that the CoL metadata needs potentially to be different. We can have different metadata in a release without effecting the original datasets metadata. But we currently lack tooling to keep that updated. How about a metadata patch per source dataset that gets applied on a field by field basis during a release? This allows to override fields we want to control, but otherwise allows new information to come through from the sources.

**Comment by mdoering** [comment] 2020-02-25 09:16
Just saw that the [UI does not deal with the dataset lock yet](https://github.com/Sp2000/colplus-frontend/issues/502).

**Comment by mdoering** [comment] 2020-10-07 09:28
duplicate of #184

**Closed by mdoering** 2020-10-07 09:28 UTC
Labels: enhancement, metadata
