### ISSUE TITLE
Authorship strings truncated to 50 characters

### ISSUE THREAD

**Issue by aoern** [CatalogueOfLife/data#148] opened 2020-06-24 16:02 UTC
Hi @yroskov and @gdower !

Again, this is an old issue. The authorship strings in datasets that have been updated through automated process are truncated to 50 characters. There are ~2100 truncations in WoRMS, SF and Psyl'list databases.
Is this automated update process going to start in CoL+, too? If yes, this bug should be fixed. Secondly, are there any plans how to fix the data in CoL+? A full dataset import may be needed.
BTW. The CoL data and WoRMS data (as seen via WoRMS pages) do not seem to be in good sync, also for other reasons.

**Comment by gdower** [comment] 2020-06-24 16:36
Hi @aoern--thank you for your feedback! The data truncation issue is really a problem with the old infrastructure which produces the DarwinCore archive that you are using. [The Species Fungorum author strings are not truncated in the Clearinghouse.](https://data.catalogue.life/dataset/2073/taxon/810279) [Creating a new DarwinCore exporter is planned](https://github.com/CatalogueOfLife/backend/issues/650).

We haven't re-established the pipelines to update WoRMS and Paris (including Psyl'list) databases yet but aim to do so in coming months, so the author strings will still be truncated for those databases until we develop new conversion scripts and re-import them. I'm going to close this issue, because it's a [duplicate of the other data truncation issue](https://github.com/CatalogueOfLife/data/issues/145). I'll assign the other issue to the annual edition project to do list, because ideally we will aim to fix the data truncation issues by the next annual edition release.

**Closed by gdower** 2020-06-24 16:36 UTC
Labels: feedback
